insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Elvera', 'ahymans0@printfriendly.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Essy', 'eprimarolo1@cyberchimps.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Ellie', 'niacoboni2@phpbb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Jodee', 'rbrunetti3@google.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Marcille', 'jvarrow4@php.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Devi', 'jphilpin5@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Morgen', 'achallicum6@bloomberg.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Emanuele', 'cedworthie7@seesaa.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Locke', 'dockwell8@chicagotribune.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Colleen', 'gjerrems9@acquirethisname.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Leoline', 'vpidona@sogou.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Claudius', 'cmcphaterb@163.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Sonny', 'slisimorec@printfriendly.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Sky', 'opoyled@zdnet.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Hannis', 'ibrotherheede@friendfeed.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Tanhya', 'asapseedf@oakley.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Dagny', 'hhugoning@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Raymund', 'bmatschukh@umn.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Erinn', 'myerletti@cpanel.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'William', 'jschulzj@pinterest.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Davidde', 'mheakinsk@latimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Jehu', 'gmalcolmsonl@google.com.hk');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Christen', 'bbettem@loc.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Mal', 'lecklyn@dyndns.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Christa', 'gclemono@columbia.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Lynette', 'thesserp@rambler.ru');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Thibaut', 'vshawcroftq@nih.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Feliza', 'ldysertr@indiatimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Barbra', 'sdonahos@uiuc.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Juliane', 'kblythingt@prweb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Efrem', 'hcherringtonu@gov.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Virgie', 'ldumberellv@state.tx.us');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Kris', 'gshutlew@mtv.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Lamar', 'rantognozziix@multiply.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Gisela', 'srojasy@yolasite.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Florrie', 'dhindshawz@sogou.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Selestina', 'abancroft10@google.nl');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Clyve', 'amunehay11@people.com.cn');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Oralia', 'aconway12@wordpress.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Stavros', 'rfordy13@google.cn');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Goldia', 'smccullogh14@ted.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Chan', 'jtuhy15@fotki.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Reta', 'ltewkesberrie16@cocolog-nifty.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Patty', 'kbriddock17@washington.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Kimbell', 'agiddings18@facebook.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Gavan', 'dmc19@themeforest.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Nils', 'kburchmore1a@youtube.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Bailie', 'cburnhams1b@usnews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Reena', 'bbonnesen1c@pagesperso-orange.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Rafi', 'mbreach1d@amazon.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Daisy', 'mkikke1e@studiopress.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Elaine', 'mhache1f@indiegogo.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Esdras', 'gmargrem1g@de.vu');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Jeanie', 'vwalklate1h@columbia.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'William', 'lsambals1i@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Geri', 'oarnaut1j@cbslocal.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Saundra', 'jorodane1k@imdb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Linoel', 'astevings1l@twitpic.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Mignonne', 'hreame1m@feedburner.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Adel', 'ilevermore1n@weibo.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'William', 'bgehrtz1o@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Erhard', 'cleask1p@psu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Maryl', 'pbeadles1q@seattletimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Dwain', 'astreater1r@rediff.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Orrin', 'ghummerston1s@guardian.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Melinde', 'mmorena1t@pbs.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Adina', 'alambart1u@microsoft.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Gabey', 'gashurst1v@webeden.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Rebecca', 'ctullett1w@imdb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Axel', 'dahearne1x@hibu.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Olivia', 'apammenter1y@mayoclinic.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Lavena', 'kraiston1z@oracle.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Parrnell', 'jshemwell20@drupal.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Minerva', 'tcurrey21@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Margie', 'dsaunderson22@guardian.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Wynny', 'mcarluccio23@cpanel.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Aldric', 'ocunnington24@webnode.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Prent', 'lgaiger25@amazon.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Abrahan', 'bmcgreil26@ucoz.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Sena', 'rcoots27@usgs.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Sebastiano', 'taslin28@telegraph.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Chase', 'loxenbury29@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Vania', 'amarder2a@sphinn.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Stoddard', 'vharrild2b@wunderground.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Kristoffer', 'paimson2c@google.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Rozella', 'aedghinn2d@ezinearticles.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Renaud', 'gnourse2e@google.com.br');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Sloane', 'bkingcott2f@rambler.ru');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Laurella', 'mfowkes2g@nydailynews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Laurie', 'ebunt2h@discovery.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Marquita', 'tprati2i@cmu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Glynnis', 'asimeonov2j@posterous.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Dita', 'fboustead2k@e-recht24.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Wendy', 'skubicek2l@weather.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Adam', 'cburrells2m@hugedomains.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Evonne', 'ele2n@amazon.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Ardys', 'eskottle2o@ustream.tv');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Marybeth', 'bbyrom2p@illinois.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Dee dee', 'bstandell2q@163.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Tallulah', 'svousden2r@addtoany.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Sabine', 'cde2s@google.pl');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Page', 'ztrice2t@studiopress.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Crystie', 'aharrod2u@ucoz.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Carr', 'hknutsen2v@unicef.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Miguel', 'cjeandel2w@technorati.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Eugenius', 'abusfield2x@mit.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Wally', 'pcanon2y@msu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Ursa', 'gjessen2z@ox.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Aigneis', 'efitzpatrick30@illinois.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Karola', 'zmegainey31@uol.com.br');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Ulric', 'ddury32@sun.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Andre', 'abrunsdon33@marriott.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Yance', 'fbilson34@telegraph.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Meade', 'fpimblott35@wix.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Ravi', 'cbunclark36@dell.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Nathan', 'astanning37@symantec.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Virgilio', 'atinghill38@ebay.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Guy', 'fpervoe39@intel.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Amity', 'hfullard3a@blogs.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Gilligan', 'tmanderson3b@free.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Skell', 'scartner3c@alibaba.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Clarey', 'cdonoghue3d@unblog.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Tine', 'lburth3e@t-online.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Melodie', 'pemerine3f@unblog.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Karolina', 'spurselowe3g@sakura.ne.jp');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Sigrid', 'wheliot3h@yahoo.co.jp');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Marcellina', 'nmarte3i@etsy.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Eileen', 'tdarnbrook3j@apache.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Jacklin', 'xbattista3k@360.cn');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Salem', 'wwestmerland3l@elegantthemes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Cordie', 'bchue3m@ebay.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Tripp', 'dstaff3n@ezinearticles.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Osborn', 'btinniswood3o@t-online.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Waite', 'khabbal3p@skyrock.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Clarie', 'wdi3q@storify.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Maje', 'vacton3r@samsung.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Francois', 'vgibbard3s@soundcloud.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Roosevelt', 'fbrenstuhl3t@dropbox.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Leonanie', 'fhallut3u@state.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Madelaine', 'jshaw3v@ihg.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Gilligan', 'bcallicott3w@tripod.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Thor', 'cbertenshaw3x@google.co.jp');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Oralla', 'gbaggarley3y@123-reg.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Leonidas', 'kszymaniak3z@angelfire.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Orran', 'cszymanek40@tuttocitta.it');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Judy', 'acunde41@buzzfeed.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Jaime', 'nriccio42@si.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Aloisia', 'agourdon43@foxnews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Therine', 'rklain44@vimeo.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Kailey', 'lcapin45@amazon.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Westleigh', 'spaoletti46@statcounter.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Andonis', 'lmitchelson47@usnews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Devin', 'sgreguol48@telegraph.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Park', 'bhanna49@sbwire.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Raviv', 'fmacdonagh4a@youtube.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Alfie', 'mpitbladdo4b@xrea.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Marianne', 'ktomlins4c@wunderground.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Janie', 'wchristley4d@123-reg.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Bree', 'wmackissack4e@homestead.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Nerta', 'ariatt4f@auda.org.au');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Moreen', 'hangel4g@census.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Lorain', 'schandlar4h@ibm.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Jeramie', 'pkinleyside4i@bing.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Lyndy', 'dcullotey4j@free.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Stevy', 'bsheraton4k@a8.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Frannie', 'rcowen4l@boston.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Fulvia', 'scobbe4m@goo.gl');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Ansell', 'aallchorn4n@adobe.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Nathanael', 'ihalliburton4o@paginegialle.it');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Benedikt', 'zlaxe4p@webeden.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Berget', 'vattenbarrow4q@wunderground.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Muriel', 'fbramall4r@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Dannie', 'cinnman4s@ameblo.jp');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Jake', 'cdriffield4t@about.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Georgie', 'ciashvili4u@soundcloud.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Madeline', 'rchasemoore4v@woothemes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Travers', 'khendriksen4w@virginia.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Ardeen', 'aorable4x@ning.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Roda', 'msteffans4y@parallels.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Kelly', 'mcorstorphine4z@npr.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Alvin', 'cbridgstock50@ovh.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Cordelia', 'spaule51@msu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Starlene', 'ayashnov52@facebook.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Blythe', 'aechallie53@smugmug.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Carmen', 'whesey54@ihg.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Claudio', 'gcocksedge55@archive.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Erina', 'bwoodward56@shinystat.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Kerry', 'nmeltetal57@marriott.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Cheston', 'aganforthe58@imageshack.us');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'David', 'mbenstead59@sbwire.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Petronia', 'tjoust5a@ted.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Hugues', 'tguerrin5b@uol.com.br');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Gaspard', 'opearl5c@furl.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Wenona', 'lklamman5d@google.com.br');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Rosalia', 'gsenner5e@sourceforge.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Martie', 'lswinyard5f@admin.ch');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Janis', 'iodonohue5g@php.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Timoteo', 'rpardie5h@dagondesign.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Russ', 'dkrzyzowski5i@stanford.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Kylie', 'rhodges5j@ibm.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Carrissa', 'ahymans0@printfriendly.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Ganny', 'eprimarolo1@cyberchimps.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Guthrie', 'niacoboni2@phpbb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Ruthanne', 'rbrunetti3@google.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Flor', 'jvarrow4@php.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Allissa', 'jphilpin5@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Ayn', 'achallicum6@bloomberg.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Adel', 'cedworthie7@seesaa.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Ethyl', 'dockwell8@chicagotribune.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Carlyle', 'gjerrems9@acquirethisname.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Nicoli', 'vpidona@sogou.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Brew', 'cmcphaterb@163.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hedgehog', 'Drake', 'slisimorec@printfriendly.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Mar', 'opoyled@zdnet.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Jerrilyn', 'ibrotherheede@friendfeed.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Olga', 'asapseedf@oakley.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Fanchette', 'hhugoning@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Siana', 'bmatschukh@umn.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Turtle', 'Tomkin', 'myerletti@cpanel.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Even', 'jschulzj@pinterest.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Stuart', 'mheakinsk@latimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Pig', 'Lenka', 'gmalcolmsonl@google.com.hk');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Goldina', 'bbettem@loc.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Noami', 'lecklyn@dyndns.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Elisha', 'gclemono@columbia.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Russell', 'thesserp@rambler.ru');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Nannette', 'vshawcroftq@nih.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Meryl', 'ldysertr@indiatimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Earlie', 'sdonahos@uiuc.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Ailyn', 'kblythingt@prweb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Lian', 'hcherringtonu@gov.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Elisabetta', 'ldumberellv@state.tx.us');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Thurston', 'gshutlew@mtv.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Putnam', 'rantognozziix@multiply.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Spider', 'Carita', 'srojasy@yolasite.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Iguana', 'Brunhilde', 'dhindshawz@sogou.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Pip', 'abancroft10@google.nl');
insert into is_of (pet_type, pet_name, owner_email) values ('Hermit Crab', 'Inglebert', 'amunehay11@people.com.cn');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Pamela', 'aconway12@wordpress.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Gwendolin', 'rfordy13@google.cn');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Jammal', 'smccullogh14@ted.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Cody', 'jtuhy15@fotki.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Francisco', 'ltewkesberrie16@cocolog-nifty.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Chrissy', 'kbriddock17@washington.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Jaquith', 'agiddings18@facebook.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Noak', 'dmc19@themeforest.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Marissa', 'kburchmore1a@youtube.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Shepperd', 'cburnhams1b@usnews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Jaclin', 'bbonnesen1c@pagesperso-orange.fr');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Dulcinea', 'mbreach1d@amazon.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Barth', 'mkikke1e@studiopress.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Cordy', 'mhache1f@indiegogo.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Petronella', 'gmargrem1g@de.vu');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Cara', 'vwalklate1h@columbia.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Suzi', 'lsambals1i@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Stick-Bugs', 'Steve', 'oarnaut1j@cbslocal.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Pearle', 'jorodane1k@imdb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Aubine', 'astevings1l@twitpic.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Lexy', 'hreame1m@feedburner.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Patrick', 'ilevermore1n@weibo.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Jedidiah', 'bgehrtz1o@businessinsider.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Janice', 'cleask1p@psu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Arron', 'pbeadles1q@seattletimes.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Raleigh', 'astreater1r@rediff.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Ant Farm', 'Tuckie', 'ghummerston1s@guardian.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Dinnie', 'mmorena1t@pbs.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Sebastien', 'alambart1u@microsoft.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Cat', 'Lorilee', 'gashurst1v@webeden.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Aubrey', 'ctullett1w@imdb.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Emelita', 'dahearne1x@hibu.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Dotti', 'apammenter1y@mayoclinic.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Reyna', 'kraiston1z@oracle.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Yorgo', 'jshemwell20@drupal.org');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Stephan', 'tcurrey21@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Mantis', 'Wilhelmine', 'dsaunderson22@guardian.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Janean', 'mcarluccio23@cpanel.net');
insert into is_of (pet_type, pet_name, owner_email) values ('Dog', 'Guillema', 'ocunnington24@webnode.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Hallie', 'lgaiger25@amazon.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Newt', 'Christen', 'bmcgreil26@ucoz.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Sheep', 'Reiko', 'rcoots27@usgs.gov');
insert into is_of (pet_type, pet_name, owner_email) values ('Alpaca', 'Suzann', 'taslin28@telegraph.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Snake', 'Kylila', 'loxenbury29@cam.ac.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Kile', 'amarder2a@sphinn.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Rabbit', 'Eda', 'vharrild2b@wunderground.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Filmer', 'paimson2c@google.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Gecko', 'Juliane', 'aedghinn2d@ezinearticles.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Fish', 'Mal', 'gnourse2e@google.com.br');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Irv', 'bkingcott2f@rambler.ru');
insert into is_of (pet_type, pet_name, owner_email) values ('Toad', 'Bonni', 'mfowkes2g@nydailynews.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Salamander', 'Israel', 'ebunt2h@discovery.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Berenice', 'tprati2i@cmu.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Gerbil', 'Menard', 'asimeonov2j@posterous.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Hamster', 'Jakie', 'fboustead2k@e-recht24.de');
insert into is_of (pet_type, pet_name, owner_email) values ('Tortoise', 'Samuel', 'skubicek2l@weather.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Frog', 'Norby', 'cburrells2m@hugedomains.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Horse', 'Jehanna', 'ele2n@amazon.co.uk');
insert into is_of (pet_type, pet_name, owner_email) values ('Bird', 'Gasper', 'eskottle2o@ustream.tv');
insert into is_of (pet_type, pet_name, owner_email) values ('Rat', 'Jade', 'bbyrom2p@illinois.edu');
insert into is_of (pet_type, pet_name, owner_email) values ('Ferret', 'Wylie', 'bstandell2q@163.com');
insert into is_of (pet_type, pet_name, owner_email) values ('Guinea Pig', 'Car', 'svousden2r@addtoany.com');
