insert into pet_type (name, base_daily_price) values ('Fish', '64.76');
insert into pet_type (name, base_daily_price) values ('Dog', '95.18');
insert into pet_type (name, base_daily_price) values ('Cat', '108.60');
insert into pet_type (name, base_daily_price) values ('Hamster', '79.70');
insert into pet_type (name, base_daily_price) values ('Rabbit', '24.14');
insert into pet_type (name, base_daily_price) values ('Bird', '24.20');
insert into pet_type (name, base_daily_price) values ('Guinea Pig', '83.95');
insert into pet_type (name, base_daily_price) values ('Turtle', '121.99');
insert into pet_type (name, base_daily_price) values ('Tortoise', '43.50');
insert into pet_type (name, base_daily_price) values ('Frog', '106.75');
insert into pet_type (name, base_daily_price) values ('Toad', '135.23');
insert into pet_type (name, base_daily_price) values ('Gerbil', '85.57');
insert into pet_type (name, base_daily_price) values ('Hermit Crab', '94.64');
insert into pet_type (name, base_daily_price) values ('Ant Farm', '148.53');
insert into pet_type (name, base_daily_price) values ('Rat', '39.70');
insert into pet_type (name, base_daily_price) values ('Horse', '115.22');
insert into pet_type (name, base_daily_price) values ('Snake', '32.30');
insert into pet_type (name, base_daily_price) values ('Gecko', '29.05');
insert into pet_type (name, base_daily_price) values ('Ferret', '105.09');
insert into pet_type (name, base_daily_price) values ('Spider', '88.62');
insert into pet_type (name, base_daily_price) values ('Iguana', '101.91');
insert into pet_type (name, base_daily_price) values ('Mantis', '91.22');
insert into pet_type (name, base_daily_price) values ('Stick-Bugs', '95.49');
insert into pet_type (name, base_daily_price) values ('Hedgehog', '146.83');
insert into pet_type (name, base_daily_price) values ('Newt', '36.53');
insert into pet_type (name, base_daily_price) values ('Salamander', '148.71');
insert into pet_type (name, base_daily_price) values ('Pig', '25.02');
insert into pet_type (name, base_daily_price) values ('Sheep', '97.43');
insert into pet_type (name, base_daily_price) values ('Alpaca', '44.21');